### ISSUE TITLE
GaugeBand gradientRatio should be double array

### ISSUE THREAD

**Issue by dardison** [GwtMaterialDesign/gwt-material-amcharts#10]
According to this: https://docs.amcharts.com/3/javascriptcharts/GaugeBand

the gradientRatio of GaugeBand should be double[] in java, but It is defined as int[]

**Comment by kevzlou7979** [comment]
Fixed via https://github.com/GwtMaterialDesign/gwt-material-amcharts/commit/c3473491f91aff8a41f74b16094f8c4bcda14ee5. Thanks for the catch
