### ISSUE TITLE
Dynamically loading chart datasets

### ISSUE THREAD

**Issue by andreaht** [GwtMaterialDesign/gwt-material-amcharts#6]
To dinamically load dataset the javascript method `AmCharts.loadFile` is missing.
See example here: [https://www.amcharts.com/kbase/dynamically-loading-chart-datasets/](url).
Note that the method is prent in file dataloader.js, but method is not available in GWT.

**Comment by kevzlou7979** [comment]
Ok will add this up to you. Note that we are working on new AmchartsV4 version but currently we still push bug fixes to the current GMD Amcharts

**Comment by kevzlou7979** [comment]
Fixed via https://github.com/GwtMaterialDesign/gwt-material-amcharts/commit/3da656cc7d8352b52d39a690f7a9b0be28bf35da

**Comment by andreaht** [comment]
I'am not getting this fix work: I have tried: 
`AmCharts.loadFile(Url, o -> {`
`            logger.log(Level.INFO, "lambda ChartWindowView.liveUpdateChart reached!");`
`            chart.setDataProvider(AmCharts.parseJSON(o));`
`            chart.validateData();`
`        } );`

But In JS debugger i got the error:

> >Exception: java.lang.JsException: TypeError: Cannot read property 'call' of undefined
  TypeError: Cannot read property 'call' of undefined
    at XMLHttpRequest.r.onreadystatechange (<anonymous>:1:5607)

**Comment by andreaht** [comment]
Thank you Mark for re-opening the issue. 
You may try to implement those 2 examples in the AMChartsDemo project to verify the the fixes:
https://codepen.io/amcharts/pen/azpbWp
http://jsfiddle.net/amcharts/ATQUm/

**Comment by kevzlou7979** [comment]
Oh I think we missed one more additional param (Second)
```
 AmCharts.loadFile(dataset_url, {}, function(data) {
    chart.dataProvider = AmCharts.parseJSON(data);
    chart.validateData();
  });
```

**Comment by kevzlou7979** [comment]
I can't find in the documentation the loadFile, https://docs.amcharts.com/3/javascriptcharts/AmChart

**Comment by andreaht** [comment]
I found some documentation here: https://github.com/amcharts/dataloader/#using-data-loaders-standalone-functions

**Comment by andreaht** [comment]
For live updatind a chart you must instead use 

> chart.dataProvider

but in the porting of the library it seems to not being fully supported: You can set a data provider to a chart, but it's not possible to get it back for live updating. In detail it's not possible to use functions:

> chart.dataProvider.shift();
> chart.dataProvider.push({        });

As showed in this example: http://jsfiddle.net/amcharts/ATQUm/

It would be nice to add this example to the AMChartsDemo..

**Comment by kevzlou7979** [comment]
Thanks for the link, will update the API and the Chart Demo once I got free time.

**Comment by andreaht** [comment]
I've forked the project and patched the issue. There is a pending pull request to close the issue.
